// SPDX-FileCopyrightText: Copyright Orangebot, Inc. and Medplum contributors
// SPDX-License-Identifier: Apache-2.0

/** @typedef {{ name: string, title: string, description: string, files: string[], upstream?: string, categories?: string[] }} RegistryItemSpec */

/** @type {RegistryItemSpec[]} */
export const items = [
  {
    name: 'medplum-link',
    title: 'MedplumLink',
    description: 'In-app FHIR resource/reference/string link that navigates unless the click is auxiliary.',
    files: ['components/medplum/medplum-link.tsx'],
    upstream: 'MedplumLink',
    categories: ['navigation'],
  },
  {
    name: 'link-tabs',
    title: 'LinkTabs',
    description: 'Tabs whose values are URL segments; left-click navigates, aux-click keeps the native link.',
    files: ['components/medplum/link-tabs.tsx'],
    upstream: 'LinkTabs',
    categories: ['navigation'],
  },
  {
    name: 'resource-avatar',
    title: 'ResourceAvatar',
    description: 'Avatar for a FHIR resource or reference, with optional MedplumLink wrapper.',
    files: ['components/medplum/resource-avatar.tsx', 'components/medplum/resource-avatar-utils.ts'],
    upstream: 'ResourceAvatar',
    categories: ['fhir', 'display'],
  },
  {
    name: 'resource-name',
    title: 'ResourceName',
    description: 'Display string for a FHIR resource or reference, optionally linked.',
    files: ['components/medplum/resource-name.tsx'],
    upstream: 'ResourceName',
    categories: ['fhir', 'display'],
  },
  {
    name: 'resource-badge',
    title: 'ResourceBadge',
    description: 'ResourceAvatar plus ResourceName in a compact row.',
    files: ['components/medplum/resource-badge.tsx'],
    upstream: 'ResourceBadge',
    categories: ['fhir', 'display'],
  },
  {
    name: 'status-badge',
    title: 'StatusBadge',
    description: 'FHIR status string rendered as a colored Badge; hyphens become spaces.',
    files: ['components/medplum/status-badge.tsx'],
    upstream: 'StatusBadge',
    categories: ['fhir', 'display'],
  },
  {
    name: 'error-boundary',
    title: 'ErrorBoundary',
    description: 'Class error boundary that shows a destructive Alert and clears on navigation.',
    files: ['components/medplum/error-boundary.tsx'],
    upstream: 'ErrorBoundary',
    categories: ['layout'],
  },
  {
    name: 'loading',
    title: 'Loading',
    description: 'Full-viewport centered Spinner.',
    files: ['components/medplum/loading.tsx'],
    upstream: 'Loading',
    categories: ['layout'],
  },
  {
    name: 'operation-outcome-alert',
    title: 'OperationOutcomeAlert',
    description: 'Destructive Alert listing OperationOutcome issues (or a raw issues array).',
    files: ['components/medplum/operation-outcome-alert.tsx'],
    upstream: 'OperationOutcomeAlert',
    categories: ['forms'],
  },
  {
    name: 'unavailable-note',
    title: 'UnavailableNote',
    description: 'Inline note with a tooltip explaining why a field or suggestion is unavailable.',
    files: ['components/medplum/unavailable-note.tsx'],
    upstream: 'UnavailableNote',
    categories: ['forms'],
  },
  {
    name: 'scroll-to-top',
    title: 'ScrollToTop',
    description: 'Scrolls the window to the top when the react-router pathname changes.',
    files: ['components/medplum/scroll-to-top.tsx'],
    upstream: 'ScrollToTop',
    categories: ['navigation'],
  },
  {
    name: 'info-bar',
    title: 'InfoBar',
    description: 'Horizontal key/value strip (InfoBar, Entry, Key, Value).',
    files: ['components/medplum/info-bar.tsx'],
    upstream: 'InfoBar',
    categories: ['layout'],
  },
  {
    name: 'description-list',
    title: 'DescriptionList',
    description: 'Two-column description list with an optional compact layout.',
    files: ['components/medplum/description-list.tsx'],
    upstream: 'DescriptionList',
    categories: ['layout'],
  },
  {
    name: 'note-display',
    title: 'NoteDisplay',
    description: 'Stack of FHIR Annotation notes as blockquotes with optional cite.',
    files: ['components/medplum/note-display.tsx'],
    upstream: 'NoteDisplay',
    categories: ['fhir', 'display'],
  },
  {
    name: 'logo',
    title: 'Logo',
    description: 'Medplum SVG logo, overridable via MEDPLUM_LOGO_URL.',
    files: ['components/medplum/logo.tsx'],
    upstream: 'Logo',
    categories: ['layout'],
  },
  {
    name: 'array-add-button',
    title: 'ArrayAddButton',
    description: 'Add control for schema-driven arrays (labeled button or icon-only).',
    files: ['components/medplum/array-add-button.tsx'],
    upstream: 'buttons/ArrayAddButton.tsx',
    categories: ['forms'],
  },
  {
    name: 'array-remove-button',
    title: 'ArrayRemoveButton',
    description: 'Remove control for schema-driven arrays.',
    files: ['components/medplum/array-remove-button.tsx'],
    upstream: 'buttons/ArrayRemoveButton.tsx',
    categories: ['forms'],
  },
];
